#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDdvfh8mVX/cpWM6bSgbuYKj8UcepDjiKcshUxth16kW6ZP0MIujduApEvKoKQ/IB1PhPKwdhlqRVb0Ekzh9NI5S3MCdgfCHFdAuLnyfEIEvi11I7Xg7LrfGSc8N1C9ZLBVOUpPnDW9gcCl0lw8go32h0CYU+E5dO9MwQmNX5GThu/0L05VghYBsxEqU8xcVtIF21xVYv6u0W4OhlLN4nFfI9HJwDDar469EsoJVS3dvVW3f0zMAD1k173SgtehU/Rfoi1MeBTlnxn/bzPi3H/Q0Gbp6hnXfc1RtnfSifH00YHXF/LQq6Bho6ITbEN2IFSw8i6WPgO/XSZQVkFCkF2vynqLYq/4zaG8tiHtkrk0QjKe3IVSAKHMTJxxe2wK4DWzi7++6yR/f64AUChUHdEGLFJ6HkbZIPGZScMS1f0y6Xl3M6xbqBEvtymwZSjig5LtENnXuO58evq4Sgt1gwmke4LO2g7G12g+xOlU4mNu0v/f9+PqMdVzGumd/s0QdRc= sibon@Sibonelo-HP

# Downloads the golang package
packages:
  - golang-go

# Sets the GOPATH & downloads the demo payload
runcmd:
  - sudo su terraform
  - sudo mkdir /home/terraform/go
  - sudo chown terraform:hashicorp /home/terraform/go
  - export GOPATH=/home/terraform/go
  - go get github.com/hashicorp/learn-go-webapp-demo
